module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontSize: {
        navText: "1rem",
        heroTitle: "5rem",
        heroSubTitle: "1.875rem",
        nfTitle: "2rem",
        nfProductTitle: "1rem",
      },
      colors: {
        nfMain: "#3BB77E",
        nfMainLight: "#DEF9EC",
        nfDark: "#253D4E",
        nfDarkGrey: "#7E7E7E",
        nfGrey: "#adadad",
        // blue: "#0d6efd",
        // indigo: "#6610f2",
        // purple: "#6f42c1",
        // pink: "#d63384",
        // red: "#dc3545",
        // orange: "#fd7e14",
        // yellow: "#ffc107",
        // green: "#198754",
        // teal: "#20c997",
        // cyan: "#0dcaf0",
        // white: "#fff",
        // gray: "#6c757d",
        // dark: "#343a40",
        // primary: "#0d6efd",
        // secondary: "#6c757d",
        // success: "#198754",
        // info: "#0dcaf0",
        // warning: "#ffc107",
        // danger: "#dc3545",
        // light: "#f8f9fa",
        // dark: "#212529",
      },
    },
  },
  plugins: [],
};
